### PR TITLE
BugBox QR Login Code and Database Integration

### PR DESCRIPTION
**Pull request by daezel**
- Prepared a QR Code Login for Bugbox
- Generated QR Code based on Unique ID of student's info
- Created tabs for different things
- Integrated sqlite3 database
- Added the options to download QR code and export database csv

### CODE REVIEW

**Comment by daezel** [comment]
Added the multiple tabs functionality in the file upload task.

**Comment by daezel** [comment]
**Updated Staff Login Features & QR Code Enhancements**

**Staff Login Enhancements:**

1. Added the ability for the admin to sign up new staff members with a custom role (user/admin).
2. Introduced functionality to remove existing staff members.
3. Admin can now change their own password and update passwords for other staff members.
4. Displayed a table of all staff members (with usernames and passwords) for admin view only.
5. Differentiated functions between admin and user roles:
     -  Admin-specific functions: adding/removing staff members, viewing all staff details, changing other staff passwords.
     - User-specific functions: viewing student database, updating own password.
   
**QR Code Functionality:**

1. Download all QR codes as a zip file with the unique ID embedded as a caption.
2. Fixed alignment issues for QR code captions and optimized the generation of QR codes.

**Database Enhancements:**

1. Created reusable functions for opening and closing database connections.
2. Optimized database queries and transactions to avoid redundancy.

**Comment by ben-AI-cybersec** [comment]
@AmirZandiehprojects could you please review this latest version so I can merge?

**Comment by AmirZandiehprojects** [comment]
@daezel Thank you for your recent updates. I've reviewed the changes and have some important feedback make sure you check them out :
1.Critical Security Issue: In db.py, you're storing the admin password in plaintext or at least it looks like it so let me know why is that ;
cursor.execute('''
INSERT INTO staff (username, password, role) VALUES (?, ?, ?)
''', ('dylan', 'dylanBugbox', 'admin'))
This is a severe security risk. Never store passwords in plaintext. Use a secure hashing algorithm like bcrypt.

2.SQL Injection Vulnerability: In game_login.py, the store_student_in_db function is vulnerable to SQL injection: 
c.execute('''
INSERT INTO students (first_name, last_name, grade, class_letter, roll_number, teacher_first_name, teacher_last_name, unique_id)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
''', (first_name, last_name, grade, class_letter, roll_number, teacher_first_name, teacher_last_name, unique_id))
While you're using parameterized queries here, which is good, ensure all database operations throughout the code follow this pattern.

3.Potential Information Leakage: In the staff view section, you're displaying all staff members and their roles to any logged-in staff: 
cursor.execute("SELECT username, role FROM staff")
staff_members = cursor.fetchall()
Consider limiting this information based on user roles.

4.Environment Variable Handling: In the MinIO client setup, you're not checking if the environment variables are actually set: 
access_key = os.getenv('AWS_ACCESS_KEY_ID')
secret_key = os.getenv('AWS_SECRET_ACCESS_KEY')
Add checks to ensure these variables are not None before using them.

Other than that everything else looks good .

**Comment by daezel** [comment]
1. Fixed Password Hashing using bcrypt: Passwords are now correctly hashed using bcrypt when inserting new staff members into the database.
Password comparison during login is updated to work without errors.

2. Role-Based Access Control for Staff Information: In the previous implementation, after reviewing the code, it's confirmed that only admin users can view the staff information.

image
These blocks are visible only if admin is logged in

**Pull request closed without merging**
